/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_FEDIVBYZERO 1

#define HAVE_FENV_H 1

#define PACKAGE foo

#define SIZEOF_LONG 4

#define TLS __declspec(thread)

#define USE_SSE2 1

#define USE_SSSE3 1

