/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_CAIRO 1

#define HAVE_CAIRO_PDF 1

#define HAVE_CAIRO_PNG 1

#define HAVE_CAIRO_PS 1

#define HAVE_CAIRO_WIN32 1

#define PANGO_BINARY_AGE 4503

#define PANGO_INTERFACE_AGE 0

