/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define CAIRO_HAS_INTERPRETER 1

#define HAS_PIXMAN_GLYPHS 1

#define HAS_PIXMAN_r8g8b8_sRGB 1

#define HAVE_D2D1_3_H 1

#define HAVE_FCNTL_H 1

#define HAVE_FECLEAREXCEPT 1

#define HAVE_FENV_H 1

#define HAVE_INTSAFE_H 1

#define HAVE_INTTYPES_H 1

#define HAVE_IO_H 1

#define HAVE_MKDIR 1

#define HAVE_RAISE 1

#define HAVE_SETJMP_H 1

#define HAVE_SIGNAL_H 1

#define HAVE_STDINT_H 1

#undef HAVE_STRNDUP

#define HAVE_SYS_STAT_H 1

#define HAVE_TIME_H 1

#define HAVE_UINT64_T 1

#define HAVE_ZLIB 1

#define SIZEOF_INT 4

#define SIZEOF_LONG 4

#define SIZEOF_LONG_LONG 8

#define SIZEOF_SIZE_T 8

#define SIZEOF_VOID_P 8

